<?php $this->headTitle('Liste des contacts'); ?>

<?php echo $this->successMessages(); ?>

<h2>Liste des contacts</h2>

<table class="table table-striped">
    <?php foreach ($this->contacts as $c) : ?>
    <tr>
        <td><?php echo $this->escape($c->getPrenom()); ?> <?php echo $this->escape($c->getNom()); ?></td>
        <td>
            <a href="<?php echo $this->myUrl('contact', 'show', array('id' => $this->escape($c->getId()))); ?>" class="btn btn-xs btn-primary">Afficher</a>
            <a href="<?php echo $this->myUrl('contact', 'update', array('id' => $this->escape($c->getId()))); ?>" class="btn btn-xs btn-warning">Modifier</a>
            <a href="<?php echo $this->myUrl('contact', 'remove', array('id' => $this->escape($c->getId()))); ?>" class="btn btn-xs btn-danger">Supprimer</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
